default: &defaults
  parallelism: 1
  working_directory: ~/SerenityJS-Cucumber-Protractor-StandAlone
  docker:
    - image: circleci/node:10.15.3-browsers
  environment:
    CHROME_BIN: "/usr/bin/google-chrome"
  dependencies:
    cache_directories:
     - ~/nvm

restore_npm_cache: &restore_npm_cache
  restore_cache:
    keys:
      - SerenityJS-Cucumber-Protractor-StandAlone-{{ .Branch }}-{{ checksum "package.json" }}
      - SerenityJS-Cucumber-Protractor-StandAlone-{{ .Branch }}-

save_npm_cache: &save_npm_cache
  save_cache:
    key: SerenityJS-Cucumber-Protractor-StandAlone-{{ .Branch }}-{{ checksum "package.json" }}
    paths:
      - "node_modules"

install_depencies_with_npm: &install_depencies_with_npm
  run:
    name: Npm Install
    command: |
      npm install
      cd serenity-develop
      npm install

build_app: &build_app
  run:
    name: Next buid
    command: |
      npm run build

start_app: &start_app
  run:
    name: Start app
    command: |
      sh -c "API_URL=http://staging-explorer-api.blockstack.xyz npm run start | tee logs/node_server.log" && sleep 15

run_tests: &run_tests
  run:
    name: Run Tests
    command: |
      cd serenity-develop
      TEST_URL=http://localhost:3000 npm run test

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - *restore_npm_cache
      - *install_depencies_with_npm
      - *save_npm_cache
      - *build_app
      - *start_app
      - *run_tests

workflows:
  version: 2
  build-and-test:
    jobs:
      - test

